### ISSUE TITLE
SVG problem

### ISSUE THREAD

**Issue by profejuanca** [openlilylib/LO-ly#15]
Hi
When I try to use svg option in OLY/Libreoffice this appear and svg is not imported to sheet.
Lilypond aparently creates the svg (LY output says Done). I can insert a SVG manually, but i need to work directly on Libreoffice Impress or Writer.
![svg_libreoffice problem](https://user-images.githubusercontent.com/12680357/30073310-4fae7508-923b-11e7-9933-7274edce55fb.png)

**Comment by profejuanca** [comment]
My Lilypond version is 2.18.2, libreoffice is 5.4.1.2, but this problem appear in libreoffice older versions too (5.2.x and 5.3.x)

**Comment by profejuanca** [comment]
Anybody have a idea of this problem?
 Thanks in advance

**Comment by profejuanca** [comment]
I forget, Oly is 0.5.5 version, but this happen in 0.5.4 too

**Comment by KlausBlum** [comment]
Your "LilyPond output" window shows that LilyPond complains about a missin "version" statement. 
(OLy still can't handle that message and aborts. Someday, I should find a solution for that. Sigh...)

Therefore, all default SVG templates contain the following line: 
#(define version-seen #t)
It supresses the output of the above warning. If you removed that line, you should add it again. 

Does that solve the problem?

Cheers, 
Klaus

**Comment by KlausBlum** [comment]
Hi profejuanca,

Your "LilyPond output" window shows that LilyPond complains about a 
missin "version" statement.
(OLy still can't handle that message and aborts. Someday, I should find 
a solution for that. Sigh...)

Therefore, all default SVG templates contain the following line:
#(define version-seen #t)
It supresses the output of the above warning. If you removed that line, 
you should add it again.

Does that solve the problem?

Cheers,
Klaus Blum



Am 05.09.2017 um 19:12 schrieb profejuanca:

**Comment by profejuanca** [comment]
Thanks Klaus, I added the \version instruction and SVG works, thanks.
