### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by joram-berger** [openlilylib/LO-ly#4]
We already discussed how to release new versions. Access to the known sourceforge page would be nice to keep the tradition. I would also suggest to add page to openlilylib.org.

Until then, I added a [Downloads](https://github.com/openlilylib/LO-ly/wiki/Downloads) page as a temporary solution. What do you think?

**Comment by uliska** [comment]
> Access to the known sourceforge page would be nice to keep the tradition. 

Yes, but maybe somewhat complicated. Unless Samuel gives us access to upload files ourselves.
An alternative approach would be to add a link to the new download location (if we agree upon one) on the original ooolilypond homepage.

> I would also suggest to add page to openlilylib.org.

This would be nice. But right now I don't really know how to proceed with that website. I had started writing a single page web app (also to learn that), but restricted this by simply removing the links to further pages. My idea would be to integrate openlilylib.org with the packages' documentation, but this is pretty far off right now - if there isn't someone coming around in GSoC ...

> Until then, I added a Downloads page as a temporary solution. What do you think?

This is a good compromise IMO.
There should be a link to it in the main README, though.

What do you think, what should we add to the README anyway?

**Comment by KlausBlum** [comment]
Ooops... of course it's 0.4.2rc7 - I'll delete the release and the tag. 
+1 for the download page!

**Comment by joram-berger** [comment]
> What do you think, what should we add to the README anyway?

I added some information to the readme in b77686f. IMO that's basically it. Should we add some developer information? How to contribute, how a release is made, ...

I would suggest to put a more verbose version (documentation) on the page to be defined. This documentation could include:

* Some more words what it is all about
* A simple example and some images
* A step by step installation process
* An explanation of the user interface
